title : Python Lectures
author: DASH (Data Analysis Support Hub)
logo: 'dash_logo.png'
description: This website presents a set of lectures on python programming provided by DASH.

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/executablebooks/quantecon-mini-example
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
